'use client';
import { ArrowLeft, ChevronDown, FileText } from 'lucide-react';
import Link from 'next/link';
import { useParams, useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { useEmployee, useEmployeeSalarySlips } from '@/lib/queries';
import { SalarySlipView } from '@/components/salary-slip-view';
import { ErrorState, LoadingSkeleton, Select } from '@/components/ui';
export default function SalarySlipPage() { const { id } = useParams<{ id: string }>(); const searchParams = useSearchParams(); const requestedSlip = searchParams.get('slip'); const employee = useEmployee(id); const slips = useEmployeeSalarySlips(id); const [selection, setSelection] = useState<{ query: string | null; value: string | null }>({ query: requestedSlip, value: null }); const selected = selection.query === requestedSlip ? selection.value : requestedSlip; if (employee.isLoading || slips.isLoading) return <LoadingSkeleton rows={8} />; if (employee.isError || slips.isError) return <ErrorState message={employee.error?.message ?? slips.error?.message} retry={() => { employee.refetch(); slips.refetch(); }} />; const selectedId = selected || slips.data?.[0]?.id; const current = slips.data?.find((slip) => slip.id === selectedId) ?? slips.data?.[0]; return <div><Link href={`/employees/${id}`} className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-[#777982] hover:text-[#ff725c]"><ArrowLeft className="h-4 w-4" />Back to profile</Link><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.17em] text-[#ff725c]">Payroll</p><h1 className="font-display text-3xl sm:text-[38px]">Salary slips</h1><p className="mt-2 text-sm text-[#777982]">A clear view of your earnings and deductions.</p></div>{slips.data?.length ? <div className="flex items-center gap-2"><FileText className="h-4 w-4 text-[#898b91]" /><Select aria-label="Select salary month" value={current?.id ?? ''} onChange={(event) => setSelection({ query: requestedSlip, value: event.target.value || null })} className="min-w-48"><option value="">Latest slip</option>{slips.data.map((slip) => <option key={slip.id} value={slip.id}>{slip.month}/{slip.year}</option>)}</Select><ChevronDown className="hidden" /></div> : null}</div>{current ? <SalarySlipView slip={{ ...current, employee: employee.data }} /> : <ErrorState message="No salary slips have been generated for this employee yet." />}</div>; }
