'use client';

import { eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, startOfMonth, startOfWeek } from 'date-fns';
import type { AttendanceRecord } from '@peopleos/types';
import { cn, StatusBadge } from './ui';

export function AttendanceCalendar({ records, month = new Date() }: { records: AttendanceRecord[]; month?: Date }) { const days = eachDayOfInterval({ start: startOfWeek(startOfMonth(month), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(month), { weekStartsOn: 1 }) }); const byDay = new Map(records.map((record) => [format(new Date(record.date), 'yyyy-MM-dd'), record])); return <div><div className="mb-3 grid grid-cols-7 text-center text-[10px] font-bold uppercase tracking-[0.12em] text-[#9a9ba0]">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day) => <div key={day} className="py-2">{day}</div>)}</div><div className="grid grid-cols-7 overflow-hidden rounded-2xl border border-[#e8e4dc]">{days.map((day) => { const record = byDay.get(format(day, 'yyyy-MM-dd')); const activeMonth = isSameMonth(day, month); return <div key={day.toISOString()} className={cn('min-h-[74px] border-b border-r border-[#eeeae4] bg-white p-2 last:border-r-0 sm:min-h-[88px] sm:p-3', !activeMonth && 'bg-[#faf9f6] text-[#c8c8c4]')}><p className={cn('text-xs font-bold', isSameDay(day, new Date()) && 'flex h-6 w-6 items-center justify-center rounded-full bg-[#ff725c] text-white')}>{format(day, 'd')}</p>{record && <div className={cn('mt-2 h-2 rounded-full sm:h-auto sm:rounded-xl sm:bg-transparent')}><span className={cn('hidden text-[10px] font-bold capitalize sm:inline', record.status === 'PRESENT' && 'text-[#208154]', record.status === 'LATE' && 'text-[#a15b00]', record.status === 'ABSENT' && 'text-[#b54334]', record.status === 'LEAVE' && 'text-[#6746b4]', record.status === 'WORK_FROM_HOME' && 'text-[#3565a2]')}><span className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-current" />{record.status.replaceAll('_', ' ').toLowerCase()}</span><span className={cn('block h-full rounded-full sm:hidden', record.status === 'PRESENT' && 'bg-[#43ad75]', record.status === 'LATE' && 'bg-[#f2a946]', record.status === 'ABSENT' && 'bg-[#e47163]', record.status === 'LEAVE' && 'bg-[#9e84df]', record.status === 'WORK_FROM_HOME' && 'bg-[#6591cf]')} /></div>}</div>; })}</div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-[11px] text-[#777982]"><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#43ad75]" />Present</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#f2a946]" />Late</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#9e84df]" />Leave</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#6591cf]" />WFH</span></div></div>; }

export function AttendanceList({ records }: { records: AttendanceRecord[] }) { return <div className="space-y-2">{records.map((record) => <div key={record.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#eeeae4] bg-white px-4 py-3"><div><p className="text-sm font-bold">{format(new Date(record.date), 'EEE, d MMM yyyy')}</p><p className="text-xs text-[#85878d]">{record.checkIn ? `${format(new Date(record.checkIn), 'h:mm a')} – ${record.checkOut ? format(new Date(record.checkOut), 'h:mm a') : 'in progress'}` : 'No time recorded'}{record.workHours ? ` · ${record.workHours}h` : ''}</p></div><StatusBadge status={record.status} /></div>)}</div>; }
