'use client';

import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Card } from './ui';

const tooltipStyle = { borderRadius: 12, border: '1px solid #e8e4dc', boxShadow: '0 8px 24px rgba(31,34,41,.08)', fontSize: 12 };
export function AttendanceTrendChart({ data }: { data: { month: string; attendance: number }[] }) { return <ResponsiveContainer width="100%" height={240}><AreaChart data={data} margin={{ top: 12, right: 6, left: -20, bottom: 0 }}><defs><linearGradient id="attendanceFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ff725c" stopOpacity={0.3} /><stop offset="100%" stopColor="#ff725c" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#efede8" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#94959a', fontSize: 11 }} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} tick={{ fill: '#94959a', fontSize: 11 }} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`${value}%`, 'Attendance']} /><Area type="monotone" dataKey="attendance" stroke="#ff725c" strokeWidth={3} fill="url(#attendanceFill)" activeDot={{ r: 5, fill: '#ff725c', stroke: '#fff' }} /></AreaChart></ResponsiveContainer>; }
export function DepartmentChart({ data }: { data: { department: string; count: number }[] }) { return <ResponsiveContainer width="100%" height={240}><BarChart data={data} layout="vertical" margin={{ top: 8, right: 12, left: 14, bottom: 2 }}><CartesianGrid horizontal={false} stroke="#efede8" /><XAxis type="number" axisLine={false} tickLine={false} allowDecimals={false} tick={{ fill: '#94959a', fontSize: 11 }} /><YAxis type="category" dataKey="department" axisLine={false} tickLine={false} width={104} tick={{ fill: '#6e7077', fontSize: 11 }} /><Tooltip cursor={{ fill: '#fffaf1' }} contentStyle={tooltipStyle} /><Bar dataKey="count" name="People" fill="#bda9fa" radius={[0, 6, 6, 0]} barSize={20} /></BarChart></ResponsiveContainer>; }
export function ChartCard({ title, description, children, action }: { title: string; description?: string; children: React.ReactNode; action?: React.ReactNode }) { return <Card className="p-5 sm:p-6"><div className="mb-2 flex items-start justify-between gap-3"><div><h2 className="font-display text-xl">{title}</h2>{description && <p className="mt-1 text-xs text-[#85878d]">{description}</p>}</div>{action}</div>{children}</Card>; }
