'use client';

import { BarChart3, Bell, BriefcaseBusiness, CalendarDays, ChevronRight, CircleHelp, ClipboardList, FileText, LayoutDashboard, LogOut, Menu, Settings2, ShieldCheck, Sparkles, Users, WalletCards, X } from 'lucide-react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { useLogout, useSession, roleCanManage } from '@/lib/queries';
import { Avatar, cn, IconButton } from './ui';

const employeeNav = [
  { href: '/dashboard', label: 'Overview', icon: LayoutDashboard },
  { href: '/attendance', label: 'My attendance', icon: CalendarDays },
  { href: '/leave', label: 'My leave', icon: ClipboardList },
  { href: '/profile', label: 'My profile', icon: BriefcaseBusiness },
];
const adminNav = [
  { href: '/admin', label: 'Overview', icon: LayoutDashboard },
  { href: '/admin/employees', label: 'Employees', icon: Users },
  { href: '/admin/attendance', label: 'Attendance', icon: CalendarDays },
  { href: '/admin/leave', label: 'Leave', icon: ClipboardList },
  { href: '/admin/payroll', label: 'Payroll', icon: WalletCards },
  { href: '/admin/users', label: 'Users & access', icon: ShieldCheck },
];

function NavItem({ href, label, icon: Icon, onClick }: { href: string; label: string; icon: typeof LayoutDashboard; onClick?: () => void }) { const pathname = usePathname(); const active = href === '/admin' || href === '/dashboard' ? pathname === href : pathname.startsWith(href); return <Link href={href} onClick={onClick} className={cn('group flex min-h-11 items-center gap-3 rounded-xl px-3.5 text-sm font-semibold transition', active ? 'bg-[#1f2229] text-white shadow-[0_5px_14px_rgba(31,34,41,0.16)]' : 'text-[#6d7078] hover:bg-[#f1f0ec] hover:text-[#1f2229]')}><Icon className={cn('h-[18px] w-[18px]', active ? 'text-[#d8f25d]' : 'text-[#92949a] group-hover:text-[#ff725c]')} /><span>{label}</span>{active && <ChevronRight className="ml-auto h-4 w-4 text-[#d8f25d]" />}</Link>; }

function Sidebar({ mobile = false, close }: { mobile?: boolean; close?: () => void }) { const { data } = useSession(); const isAdmin = roleCanManage(data?.user.role); const nav = isAdmin ? adminNav : employeeNav; return <aside className={cn('flex h-full w-[250px] shrink-0 flex-col border-r border-[#e8e4dc] bg-[#fffdf9] px-4 py-5', mobile && 'w-full border-0')}><div className="mb-8 flex items-center justify-between px-2"><Link href={isAdmin ? '/admin' : '/dashboard'} onClick={close} className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#ff725c] text-white shadow-[0_4px_0_#c84535]"><Sparkles className="h-[18px] w-[18px]" /></span><span className="text-[19px] font-black tracking-tight">PeopleOS</span></Link>{mobile && <IconButton label="Close navigation" onClick={close}><X className="h-5 w-5" /></IconButton>}</div><div className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a1a19d]">{isAdmin ? 'Workspace' : 'Your workspace'}</div><nav className="space-y-1">{nav.map((item) => <NavItem key={item.href} {...item} onClick={close} />)}</nav>{isAdmin && <><div className="mb-3 mt-8 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a1a19d]">Manage</div><nav className="space-y-1"><NavItem href="/admin/settings" label="Settings" icon={Settings2} onClick={close} /></nav></>}<div className="mt-auto rounded-2xl bg-[#eff9c7] p-4"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-[#d8f25d] text-[#5d7500]"><CircleHelp className="h-4 w-4" /></div><p className="text-sm font-bold">Need a hand?</p><p className="mt-1 text-xs leading-5 text-[#71794b]">Browse the PeopleOS help center for quick answers.</p><button className="mt-3 text-xs font-bold text-[#5d7500] underline underline-offset-2">Open help center</button></div></aside>; }

export const AdminSidebar = Sidebar;
export const EmployeeSidebar = Sidebar;

export function TopNavigation({ title, onOpenMenu }: { title?: string; onOpenMenu?: () => void }) { const { data } = useSession(); const logout = useLogout(); const [open, setOpen] = useState(false); const name = data?.user.name ?? 'PeopleOS user'; const profileHref = roleCanManage(data?.user.role) ? '/admin/settings' : '/profile'; return <header className="sticky top-0 z-20 flex min-h-[72px] items-center justify-between border-b border-[#e8e4dc] bg-[#f6f7f8]/90 px-4 backdrop-blur-md sm:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="flex min-h-10 min-w-10 items-center justify-center rounded-xl bg-white text-[#555861] lg:hidden" onClick={onOpenMenu}><Menu className="h-5 w-5" /></button>{title && <p className="hidden text-sm font-semibold text-[#6f7279] sm:block">{title}</p>}</div><div className="flex items-center gap-2"><button aria-label="Notifications" className="relative flex h-10 w-10 items-center justify-center rounded-xl text-[#777982] transition hover:bg-white"><Bell className="h-[18px] w-[18px]" /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#ff725c]" /></button><div className="relative"><button aria-expanded={open} className="flex min-h-10 items-center gap-2 rounded-xl px-1.5 text-left transition hover:bg-white" onClick={() => setOpen((value) => !value)}><Avatar name={name} size="sm" /><span className="hidden max-w-28 truncate text-xs font-bold sm:block">{name}</span><ChevronRight className={cn('hidden h-4 w-4 rotate-90 transition sm:block', open && 'rotate-[270deg]')} /></button>{open && <div className="absolute right-0 top-12 z-30 w-52 rounded-2xl border border-[#e8e4dc] bg-white p-2 shadow-xl"><div className="border-b border-[#eeeae2] px-3 py-2"><p className="truncate text-sm font-bold">{name}</p><p className="mt-0.5 text-xs text-[#85878d]">{data?.user.role.replace('_', ' ')}</p></div><Link href={profileHref} className="mt-1 flex min-h-10 items-center gap-2 rounded-xl px-3 text-sm text-[#666971] hover:bg-[#f5f4ef]">{roleCanManage(data?.user.role) ? 'Workspace settings' : 'My profile'}</Link><button className="flex min-h-10 w-full items-center gap-2 rounded-xl px-3 text-sm text-[#c24b3d] hover:bg-[#fff1ee]" onClick={() => logout.mutate()}><LogOut className="h-4 w-4" />Log out</button></div>}</div></div></header> }

export function AppShell({ children }: { children: React.ReactNode }) { const [mobileOpen, setMobileOpen] = useState(false); return <div className="min-h-dvh bg-[#f6f7f8] lg:flex"><div className="hidden lg:block"><Sidebar /></div>{mobileOpen && <div className="fixed inset-0 z-50 bg-[#1f2229]/25 lg:hidden" onClick={() => setMobileOpen(false)}><div className="h-full w-[280px] bg-[#fffdf9] shadow-2xl" onClick={(event) => event.stopPropagation()}><Sidebar mobile close={() => setMobileOpen(false)} /></div></div>}<div className="min-w-0 flex-1"><TopNavigation onOpenMenu={() => setMobileOpen(true)} /><main className="mx-auto max-w-[1480px] p-4 sm:p-7 lg:p-9">{children}</main></div></div>; }
