'use client';

import { AlertCircle, CheckCircle2, ChevronDown, Loader2, Search, Sparkles } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { ButtonHTMLAttributes, InputHTMLAttributes, SelectHTMLAttributes } from 'react';

export function cn(...classes: Array<string | false | null | undefined>) { return classes.filter(Boolean).join(' '); }
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'outline' | 'ghost' | 'danger' | 'lime'; size?: 'sm' | 'md' | 'lg'; asChild?: boolean };
export function Button({ className, variant = 'primary', size = 'md', children, disabled, ...props }: ButtonProps) { const styles = { primary: 'bg-[#ff725c] text-white hover:bg-[#e65c48] shadow-[0_5px_0_#c84535] active:translate-y-0.5 active:shadow-[0_3px_0_#c84535]', outline: 'border border-[#dedbd3] bg-white text-[#1f2229] hover:bg-[#fffaf1]', ghost: 'text-[#61646c] hover:bg-[#f3f1ec] hover:text-[#1f2229]', danger: 'border border-[#f1c9c4] bg-[#fff5f3] text-[#ba4638] hover:bg-[#ffe9e5]', lime: 'bg-[#d8f25d] text-[#1f2229] hover:bg-[#c6e447] shadow-[0_5px_0_#9ebc25] active:translate-y-0.5 active:shadow-[0_3px_0_#9ebc25]' }; const sizes = { sm: 'min-h-9 px-3 text-xs', md: 'min-h-11 px-4 text-sm', lg: 'min-h-12 px-5 text-sm' }; return <button disabled={disabled} className={cn('inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition-all disabled:pointer-events-none disabled:opacity-50', styles[variant], sizes[size], className)} {...props}>{children}</button>; }
export function IconButton({ label, className, children, ...props }: ButtonProps & { label: string }) { return <button aria-label={label} className={cn('inline-flex min-h-10 min-w-10 items-center justify-center rounded-xl text-[#61646c] transition hover:bg-[#f3f1ec] hover:text-[#1f2229] focus:outline-none focus:ring-2 focus:ring-[#ff725c]/50', className)} {...props}>{children}</button>; }
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn('min-h-11 w-full rounded-xl border border-[#dedbd3] bg-white px-3.5 text-sm text-[#1f2229] outline-none transition placeholder:text-[#a5a6ab] focus:border-[#ff725c] focus:ring-4 focus:ring-[#ff725c]/10', className)} {...props} />; }
export function Select({ className, children, ...props }: SelectHTMLAttributes<HTMLSelectElement>) { return <div className="relative"><select className={cn('min-h-11 w-full appearance-none rounded-xl border border-[#dedbd3] bg-white px-3.5 pr-9 text-sm text-[#1f2229] outline-none transition focus:border-[#ff725c] focus:ring-4 focus:ring-[#ff725c]/10', className)} {...props}>{children}</select><ChevronDown aria-hidden className="pointer-events-none absolute right-3 top-3.5 h-4 w-4 text-[#888a91]" /></div>; }
export function SearchInput({ value, onChange, placeholder = 'Search' }: { value?: string; onChange?: (value: string) => void; placeholder?: string }) { return <div className="relative min-w-56 flex-1"><Search aria-hidden className="absolute left-3.5 top-3.5 h-4 w-4 text-[#999ba2]" /><Input aria-label={placeholder} value={value} onChange={(event) => onChange?.(event.target.value)} placeholder={placeholder} className="pl-10" /></div>; }
export function Card({ className, children }: { className?: string; children: React.ReactNode }) { return <section className={cn('rounded-2xl border border-[#e8e4dc] bg-white shadow-[0_7px_24px_rgba(31,34,41,0.035)]', className)}>{children}</section>; }
export function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'green' | 'orange' | 'red' | 'blue' | 'purple' | 'lime' }) { const tones = { neutral: 'bg-[#f2f2ef] text-[#62646b]', green: 'bg-[#e2f7eb] text-[#187242]', orange: 'bg-[#fff0d9] text-[#a15b00]', red: 'bg-[#ffe8e5] text-[#b54334]', blue: 'bg-[#e6f0ff] text-[#3565a2]', purple: 'bg-[#eee9ff] text-[#6746b4]', lime: 'bg-[#eff9c7] text-[#587200]' }; return <span className={cn('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold uppercase tracking-[0.06em]', tones[tone])}><span className="h-1.5 w-1.5 rounded-full bg-current" />{children}</span>; }
export function StatusBadge({ status }: { status: string }) { const normalized = status.toLowerCase(); const tone = normalized.includes('present') || normalized.includes('paid') || normalized.includes('active') ? 'green' : normalized.includes('leave') || normalized.includes('late') || normalized.includes('processing') ? 'orange' : normalized.includes('absent') || normalized.includes('inactive') || normalized.includes('terminated') ? 'red' : normalized.includes('work') || normalized.includes('pending') ? 'blue' : 'neutral'; return <Badge tone={tone}>{status.replaceAll('_', ' ')}</Badge>; }
export function Avatar({ name, src, size = 'md' }: { name: string; src?: string | null; size?: 'sm' | 'md' | 'lg' }) { const initials = name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(); const sizeClass = { sm: 'h-8 w-8 text-[10px]', md: 'h-10 w-10 text-xs', lg: 'h-16 w-16 text-lg' }; const pixels = { sm: 32, md: 40, lg: 64 }; return src ? <Image src={src} alt={`${name} avatar`} width={pixels[size]} height={pixels[size]} unoptimized className={cn('rounded-2xl object-cover', sizeClass[size])} /> : <div aria-label={`${name} avatar`} className={cn('flex shrink-0 items-center justify-center rounded-2xl bg-[#e6ddff] font-bold text-[#6746b4]', sizeClass[size])}>{initials}</div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-[11px] font-bold uppercase tracking-[0.17em] text-[#ff725c]">{eyebrow ?? 'PeopleOS'}</p><h1 className="font-display text-3xl leading-tight text-[#1f2229] sm:text-[38px]">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm text-[#777982]">{description}</p>}</div>{action}</div>; }
export function StatCard({ label, value, hint, icon, accent = 'coral' }: { label: string; value: string | number; hint?: string; icon: React.ReactNode; accent?: 'coral' | 'lime' | 'lavender' | 'aqua' }) { const accents = { coral: 'bg-[#fff0ed] text-[#d95342]', lime: 'bg-[#eff9c7] text-[#658100]', lavender: 'bg-[#eee9ff] text-[#7050b9]', aqua: 'bg-[#e3f7f2] text-[#238773]' }; return <Card className="relative overflow-hidden p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-[#777982]">{label}</p><p className="mt-2 tabular-nums text-2xl font-bold tracking-tight text-[#1f2229]">{value}</p>{hint && <p className="mt-2 text-xs text-[#7b7d84]">{hint}</p>}</div><div className={cn('flex h-10 w-10 items-center justify-center rounded-xl', accents[accent])}>{icon}</div></div><div className="absolute -bottom-5 -right-4 h-14 w-14 rounded-full border-[7px] border-current opacity-[0.07]" /></Card>; }
export function LoadingSkeleton({ rows = 4 }: { rows?: number }) { return <div className="space-y-3" aria-label="Loading"><div className="h-4 w-40 animate-pulse rounded bg-[#eae9e5]" />{Array.from({ length: rows }).map((_, index) => <div key={index} className="h-12 animate-pulse rounded-xl bg-[#f0efec]" />)}</div>; }
export function ErrorState({ message = 'We could not load this section.', retry }: { message?: string; retry?: () => void }) { return <div className="flex min-h-44 flex-col items-center justify-center rounded-2xl border border-[#f1d0cc] bg-[#fff8f6] p-6 text-center"><AlertCircle className="mb-3 h-6 w-6 text-[#d95342]" /><p className="text-sm font-semibold text-[#8f3a30]">{message}</p>{retry && <Button variant="outline" size="sm" className="mt-4" onClick={retry}>Try again</Button>}</div>; }
export function EmptyState({ title = 'Nothing here yet', description = 'New activity will appear here when it is available.', action }: { title?: string; description?: string; action?: React.ReactNode }) { return <div className="flex min-h-52 flex-col items-center justify-center rounded-2xl border border-dashed border-[#d8d5cd] bg-[#fffdf9] p-6 text-center"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-xl bg-[#eff9c7] text-[#658100]"><Sparkles className="h-5 w-5" /></div><p className="font-semibold">{title}</p><p className="mt-1 max-w-sm text-sm text-[#7b7d84]">{description}</p>{action && <div className="mt-4">{action}</div>}</div>; }
export function FormField({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-[#61646c]">{label}</span>{children}{error && <span className="mt-1 block text-xs text-[#c24739]">{error}</span>}</label>; }
export function ProgressBar({ value, color = '#ff725c' }: { value: number; color?: string }) { return <div className="h-2 overflow-hidden rounded-full bg-[#f0eeea]"><div className="h-full rounded-full transition-all" style={{ width: `${Math.min(100, Math.max(0, value))}%`, backgroundColor: color }} /></div>; }
export function DataTableShell({ children, className }: { children: React.ReactNode; className?: string }) { return <div className={cn('scrollbar-thin overflow-x-auto', className)}><table className="w-full min-w-[680px] text-left">{children}</table></div>; }
export const DataTable = DataTableShell;
export function FilterBar({ children }: { children: React.ReactNode }) { return <div className="flex flex-col flex-wrap gap-3 sm:flex-row sm:items-center">{children}</div>; }
export function TableHeader({ children }: { children: React.ReactNode }) { return <thead className="border-b border-[#ece9e3] bg-[#fffdf9] text-[10px] font-bold uppercase tracking-[0.12em] text-[#898b91]"><tr>{children}</tr></thead>; }
export function TableCell({ children, className }: { children: React.ReactNode; className?: string }) { return <td className={cn('px-5 py-4 align-middle', className)}>{children}</td>; }
export function SelectPill({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: { label: string; value: string }[] }) { return <Select value={value} onChange={(event) => onChange(event.target.value)} className="min-h-10 rounded-full bg-[#faf9f5] py-0 text-xs font-semibold">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select>; }
export function Spinner() { return <Loader2 className="h-4 w-4 animate-spin" />; }
export function LinkButton({ href, children, variant = 'outline' }: { href: string; children: React.ReactNode; variant?: ButtonProps['variant'] }) { return <Link href={href} className={cn('inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition', variant === 'outline' ? 'border border-[#dedbd3] bg-white hover:bg-[#fffaf1]' : 'bg-[#ff725c] text-white hover:bg-[#e65c48]')}>{children}</Link>; }
export function MiniCheck({ children }: { children: React.ReactNode }) { return <div className="flex items-center gap-2 text-xs text-[#6f7279]"><CheckCircle2 className="h-4 w-4 text-[#36a36a]" />{children}</div>; }
