import type { AuthResponse, AttendanceRecord, DashboardActivity, DashboardSummary, Employee, SalarySlip, User } from '@peopleos/types';
export type Page<T> = { items: T[]; total: number; page: number; limit: number; totalPages: number };
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api';
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API_URL}${path}`, { ...init, credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, cache: 'no-store' }); if (!response.ok) { if (response.status === 401 && typeof window !== 'undefined' && !window.location.pathname.endsWith('/login')) window.location.href = '/login'; const body = await response.json().catch(() => ({})); throw new Error(Array.isArray(body.message) ? body.message[0] : body.message ?? 'Something went wrong'); } if (response.status === 204) return undefined as T; return response.json() as Promise<T>; }
export const api = {
  login: (body: { email: string; password: string; portal?: 'admin' | 'employee' }) => request<AuthResponse>('/auth/login', { method: 'POST', body: JSON.stringify(body) }), me: () => request<AuthResponse>('/auth/me'), logout: () => request<{ success: boolean }>('/auth/logout', { method: 'POST' }), refresh: () => request<AuthResponse>('/auth/refresh', { method: 'POST' }),
  summary: () => request<DashboardSummary>('/dashboard/summary'), attendanceTrend: () => request<{ month: string; attendance: number }[]>('/dashboard/attendance-trend'), departmentHeadcount: () => request<{ department: string; count: number }[]>('/dashboard/department-headcount'), recentActivity: () => request<DashboardActivity[]>('/dashboard/recent-activity'),
  employees: (params: URLSearchParams) => request<Page<Employee>>(`/employees?${params}`), departments: () => request<string[]>('/employees/departments'), employee: (id: string) => request<Employee>(`/employees/${id}`), createEmployee: (body: unknown) => request<Employee>('/employees', { method: 'POST', body: JSON.stringify(body) }), updateEmployee: (id: string, body: unknown) => request<Employee>(`/employees/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), deactivateEmployee: (id: string) => request<{ success: boolean }>(`/employees/${id}`, { method: 'DELETE' }),
  attendance: (params: URLSearchParams) => request<Page<AttendanceRecord>>(`/attendance?${params}`), attendanceSummary: (month?: number, year?: number) => request<any>(`/attendance/summary?month=${month ?? ''}&year=${year ?? ''}`), createAttendance: (body: unknown) => request<AttendanceRecord>('/attendance', { method: 'POST', body: JSON.stringify(body) }), updateAttendance: (id: string, body: unknown) => request<AttendanceRecord>(`/attendance/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  salarySlips: (params: URLSearchParams) => request<Page<SalarySlip>>(`/salary-slips?${params}`), employeeSalarySlips: (id: string) => request<SalarySlip[]>(`/employees/${id}/salary-slips`), salarySlip: (id: string) => request<SalarySlip>(`/salary-slips/${id}`), createSalarySlip: (id: string, body: unknown) => request<SalarySlip>(`/employees/${id}/salary-slips`, { method: 'POST', body: JSON.stringify(body) }), updateSalarySlip: (id: string, body: unknown) => request<SalarySlip>(`/salary-slips/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), users: () => request<User[]>('/users'), createUser: (body: unknown) => request<User>('/users', { method: 'POST', body: JSON.stringify(body) }), updateUser: (id: string, body: unknown) => request<User>(`/users/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), updateUserStatus: (id: string, isActive: boolean) => request<User>(`/users/${id}/status`, { method: 'PATCH', body: JSON.stringify({ isActive }) }),
};
export const updateUser = (id: string, body: unknown) => request<User>(`/users/${id}`, { method: 'PATCH', body: JSON.stringify(body) });
export function formatMoney(value: number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value); }
